language: objective-c
osx_image: xcode6.4
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -project CIResearch.xcodeproj -scheme CIResearch -sdk iphonesimulator8.4 -destination "OS=8.4,name=iPhone 6 Plus"
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
